apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: llm-d
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.3
  name: llm-d-redis-master
  namespace: llmd-test-manual
