apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: llm-d
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.3
  name: llm-d-redis-master
  namespace: llmd-test-manual
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp-redis
    port: 8100
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: llm-d
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: ClusterIP
