apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
    llm-d.ai/role: decode
  name: meta-llama-llama-3-2-3b-instruct-decode
  namespace: llmd-test-manual
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
      llm-d.ai/role: decode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
        llm-d.ai/role: decode
    spec:
      affinity: {}
      containers:
      - args:
        - --model
        - meta-llama/Llama-3.2-3B-Instruct
        - --port
        - "8001"
        - --max-loras
        - "2"
        - --lora
        - food-review-1
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.1.0
        imagePullPolicy: IfNotPresent
        name: vllm
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - MKNOD
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --port=8000
        - --vllm-port=8001
        - --connector=nixlv2
        image: ghcr.io/llm-d/llm-d-routing-sidecar:0.0.6
        imagePullPolicy: IfNotPresent
        name: routing-proxy
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        restartPolicy: Always
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: meta-llama-llama-3-2-3b-instruct-sa
      serviceAccountName: meta-llama-llama-3-2-3b-instruct-sa
