apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/gateway: llm-d-inference-gateway
    llm-d.ai/epp: meta-llama-llama-3-2-3b-instruct-epp
  name: meta-llama-llama-3-2-3b-instruct-epp
  namespace: llmd-test-manual
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/gateway: llm-d-inference-gateway
      llm-d.ai/epp: meta-llama-llama-3-2-3b-instruct-epp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/gateway: llm-d-inference-gateway
        llm-d.ai/epp: meta-llama-llama-3-2-3b-instruct-epp
    spec:
      containers:
      - args:
        - --poolName
        - meta-llama-llama-3-2-3b-instruct-inference-pool
        - --poolNamespace
        - llmd-test-manual
        - -v
        - "4"
        - --zap-encoder
        - json
        - --grpcPort
        - "9002"
        - --grpcHealthPort
        - "9003"
        env:
        - name: ENABLE_KVCACHE_AWARE_SCORER
          value: "true"
        - name: ENABLE_LOAD_AWARE_SCORER
          value: "true"
        - name: ENABLE_PREFIX_AWARE_SCORER
          value: "true"
        - name: ENABLE_SESSION_AWARE_SCORER
          value: "true"
        - name: KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: KVCACHE_INDEXER_REDIS_ADDR
          value: llm-d-redis-master.llmd-test-manual.svc.cluster.local:8100
        - name: LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PD_ENABLED
          value: "true"
        - name: PD_PROMPT_LEN_THRESHOLD
          value: "10"
        - name: PREFILL_ENABLE_KVCACHE_AWARE_SCORER
          value: "true"
        - name: PREFILL_ENABLE_LOAD_AWARE_SCORER
          value: "true"
        - name: PREFILL_ENABLE_PREFIX_AWARE_SCORER
          value: "true"
        - name: PREFILL_ENABLE_SESSION_AWARE_SCORER
          value: "true"
        - name: PREFILL_KVCACHE_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_KVCACHE_INDEXER_REDIS_ADDR
          value: llm-d-redis-master.llmd-test-manual.svc.cluster.local:8100
        - name: PREFILL_LOAD_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_PREFIX_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFILL_SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        - name: PREFIX_AWARE_SCORER_WEIGHT
          value: "2"
        - name: SESSION_AWARE_SCORER_WEIGHT
          value: "1"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: llm-d-hf-token
        image: ghcr.io/llm-d/llm-d-inference-scheduler:0.0.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: epp
        ports:
        - containerPort: 9002
          name: grpc
          protocol: TCP
        - containerPort: 9003
          name: grpc-health
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 9003
            service: envoy.service.ext_proc.v3.ExternalProcessor
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 256m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: meta-llama-llama-3-2-3b-instruct-epp-sa
      serviceAccountName: meta-llama-llama-3-2-3b-instruct-epp-sa
      terminationGracePeriodSeconds: 30
