apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
    llm-d.ai/role: prefill
  name: meta-llama-llama-3-2-3b-instruct-prefill
  namespace: llmd-test-manual
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
      llm-d.ai/role: prefill
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        llm-d.ai/inferenceServing: "true"
        llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
        llm-d.ai/role: prefill
    spec:
      affinity: {}
      containers:
      - args:
        - --model
        - meta-llama/Llama-3.2-3B-Instruct
        - --port
        - "8000"
        - --max-loras
        - "2"
        - --lora
        - food-review-1
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.1.0
        imagePullPolicy: IfNotPresent
        name: vllm
        ports:
        - containerPort: 80
          name: http
          protocol: TCP        
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
