apiVersion: v1
kind: Service
metadata:
  name: meta-llama-llama-3-2-3b-instruct-service-prefill
  namespace: llmd-test-manual
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ports:
  - name: nixl
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: vllm
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: meta-llama-llama-3-2-3b-instruct
    llm-d.ai/role: prefill
  sessionAffinity: None
  type: ClusterIP
