apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "<accesskey>",
      "secret_access_key": "<secretkey>",
      "endpoint_url": "https://minio.<minio_ns>.svc:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south",
      "certificate": "<cacert>"
    }
