Shared Memory
-------------

This doc explains

- free cmd `shard` value
- tmpfs
- shared memory
- /run folder
- /dev/shm folder
- emptyDir


=== 1. free cmd


free is popular cmd to check memory usage in linux. This doc start from the curiousity of `shard` value.

link:https://access.redhat.com/solutions/1138[My Red Hat Enterprise Linux system shows that I am using a lot of memory, even though nothing is running. Why?]

[source,shell]
--------------
$ free -mh
              total        used        free      shared  buff/cache   available
Mem:           7.6G        239M        5.9G        184M        1.5G        6.9G
Swap:          2.0G          0B        2.0G
--------------

**What does `shard` value mean?**

=>  __shared Memory used (mostly) by tmpfs (Shmem in /proc/meminfo, available on kernels 2.6.32, displayed as zero if not available)__ from **[man free]**



`Shmem` is all shared memory including tmpfs/memfs and ipcs shared memory.

`ipcs` is interprocess communication such as

- semaphores
- message queues
- shared memory segments

Shmem in /proc/meminfo includes ipcs stuff and thus should be equal to or less than shmem.

=== 2. tmpfs(temporary filesystem) 


- tmpfs resides in memory and/or swap partion but if swap is disabled then it uses only memory.
- The default size of tmpfs is the half of real memory size(ex, 55G memory => 26G for tmpfs)
- Everything in tmpfs is temporary in the sense that no files will be created on your hard drive.
- ramfs can create tmpfs but it can not swap and resize
- secret in docker swam/openshift will be mounted as tmpfs

__Reference doc__:

- link:https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt[tmpfs.txt]

[source]
```
Tmpfs is a file system which keeps all files in virtual memory.

Everything in tmpfs is temporary in the sense that no files will be created on your hard drive. If you unmount a tmpfs instance, everything stored therein is lost.

tmpfs puts everything into the kernel internal caches and grows and shrinks to accommodate the files it contains and is able to swap unneeded pages out to swap space. It has maximum size limits which can be adjusted on the fly via 'mount -o remount ...'

If you compare it to ramfs (which was the template to create tmpfs) you gain swapping and limit checking. Another similar thing is the RAM disk (/dev/ram*), which simulates a fixed size hard disk in physical RAM, where you have to create an ordinary filesystem on top. Ramdisks cannot swap and you do not have the possibility to resize them.

Since tmpfs lives completely in the page cache and on swap, all tmpfs pages will be shown as "Shmem" in /proc/meminfo and "Shared" in free(1). Notice that these counters also include shared memory (shmem, see ipcs(1)). The most reliable way to get the count is using df(1) and du(1).
```

=== Shared Memory


- Among processes, it can communicate via shared memory
- Shared memory help better performance (database)
- /dev/shm folder

https://www.cyberciti.biz/tips/what-is-devshm-and-its-practical-usage.html
```
/dev/shm is nothing but implementation of traditional shared memory concept. It is an efficient means of passing data between programs. One program will create a memory portion, which other processes (if permitted) can access. This will result into speeding up things on Linux.

shm / shmfs is also known as tmpfs, which is a common name for a temporary file storage facility on many Unix-like operating systems. It is intended to appear as a mounted file system, but one which uses virtual memory instead of a persistent storage device.
```


    . link:https://docs.openshift.com/container-platform/3.9/dev_guide/shared_memory.html[OpenShift Shared Memory]
- /run folder 

https://askubuntu.com/questions/169495/what-are-run-lock-and-run-shm-used-for
```
/run is, in general, a temporary filesystem (tmpfs) residing in RAM (aka "ramdisk"); its meant for storing "temporary" system or state files which may be critical but do not require persistence across reboots.

/run is actually a fairly new innovation, and was added a couple of years ago to replace the multiple tmpfs's that used to be created (including /var/lock and /dev/shm) with a single unified root tmpfs.
The main locations /run replaces are:
/var/run → /run
/var/lock → /run/lock
/dev/shm → /run/shm [currently only Debian plans to do this]
/tmp → /run/tmp [optional; currently only Debian plans to offer this] 
```


https://www.kernel.org/doc/gorman/html/understand/understand015.html
```
The filesystem comes in two variations called shm and tmpfs. They both share core functionality and mainly differ in what they are used for. shm is for use by the kernel for creating file backings for anonymous pages and for backing regions created by shmget(). This filesystem is mounted by kern_mount() so that it is mounted internally and not visible to users. tmpfs is a temporary filesystem that may be optionally mounted on /tmp/ to have a fast RAM-based temporary filesystem. A secondary use for tmpfs is to mount it on /dev/shm/. Processes that mmap() files in the tmpfs filesystem will be able to share information between them as an alternative to System V IPC mechanisms. Regardless of the type of use, tmpfs must be explicitly mounted by the system administrator.
```


