
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    serving.kserve.io/deploymentMode: Standard
  name: opt-125m-oci
spec:
  predictor:
    automountServiceAccountToken: false
    model:
      modelFormat:
        name: vLLM
      name: ""
      protocolVersion: v2
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 2Gi
          nvidia.com/gpu: "1"
      runtime: kserve-vllmserver-oci
      storageUri: hf://facebook/opt-125m