apiVersion: v1
kind: ConfigMap
metadata:
  name: facebook-opt-125m-chat-template
data:
  chat-template.jinja: |
    {% for message in messages %}
    {{ message['role'] + ': ' + message['content'] + '\n' }}
    {% endfor %}
    {% if add_generation_prompt %}
    {{ 'assistant: ' }}
    {% endif %}
---
apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: facebook-opt-125m-single
spec:
  model:
    uri: hf://facebook/opt-125m
    name: facebook/opt-125m
  replicas: 1
  router:
    gateway:
      refs:
      - name: marketing-team
        namespace: openshift-ingress
    route: {}
  template:
    volumes:
      - name: chat-template
        configMap:
          name: facebook-opt-125m-chat-template
    containers:
      - name: main
        image: docker.io/vllm/vllm-openai-cpu:v0.28.0
        args:
          - --chat-template
          - /tmp/chat-template.jinja
        volumeMounts:
          - name: chat-template
            mountPath: /tmp/chat-template.jinja
            subPath: chat-template.jinja
            readOnly: true
        securityContext:
          runAsNonRoot: false
        env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: VLLM_CPU_KVCACHE_SPACE
            value: "1"
        resources:
          limits:
            cpu: '1'
            memory: 10Gi
          requests:
            cpu: '100m'
            memory: 8Gi
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5
