apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "THEACCESSKEY",
      "secret_access_key": "e624f5f5af6678bf89806fb57ad4eea84cea8583ecfb01795168d039ac7e38a0",
      "endpoint_url": "http://minio.minio.svc:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south"
    }

