apiVersion: v1
kind: Pod
metadata: 
  name: running-pod-with-pvc
spec: 
  volumes: 
    - name: cache-pvc
      persistentVolumeClaim: 
        claimName: cache-pvc
    - name: triton-cache-pvc
      persistentVolumeClaim: 
        claimName: triton-cache-pvc 
  restartPolicy: Never
  initContainers: 
    - name: fix-volume-permissions
      image: quay.io/quay/busybox:latest
      imagePullPolicy: IfNotPresent
      securityContext: 
        allowPrivilegeEscalation: true
      resources: 
        requests: 
          memory: "64Mi"
          cpu: "250m"
        limits: 
          memory: "128Mi"
          cpu: "500m"
      command: ["sh"]
      args: ["-c", "chown -R 1001:1001 /tmp/vllm-test /tmp/triton-test"]
      volumeMounts: 
        - mountPath: "/tmp/vllm-test"
          name: cache-pvc
        - mountPath: "/tmp/triton-test"
          name: triton-cache-pvc          
  containers: 
    - name: working-pod
      image: quay.io/quay/busybox:latest
      imagePullPolicy: IfNotPresent
      securityContext: 
        allowPrivilegeEscalation: true
      resources: 
        requests: 
          memory: "1Gi"
          cpu: "1"
        limits: 
          memory: "1Gi"
          cpu: "1"
      command: ["sleep", "infinity"]
      volumeMounts: 
        - mountPath: "/tmp/vllm-test"
          name: cache-pvc
        - mountPath: "/tmp/triton-test"
          name: triton-cache-pvc           
      env: 
        - name: TRANSFORMERS_CACHE
          value: /tmp 