apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: "single-1"
spec:
  predictor:
    minReplicas: 1
    containers:
    - image: iamlovingit/bgtest:latest
      name: custom
      env:
      - name: "target"
        value: "single-1"
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: "single-2"
spec:
  predictor:
    minReplicas: 1
    containers:
    - image: iamlovingit/bgtest:latest
      name: custom
      env:
      - name: "target"
        value: "single-2"
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: "single-3"
spec:
  predictor:
    minReplicas: 1
    containers:
    - image: iamlovingit/bgtest:latest
      name: custom
      env:
      - name: "target"
        value: "single-3"
---
apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph
metadata: 
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  name: model-switch
spec:
  nodes:
    root:
      routerType: Switch
      steps:
      - serviceUrl: http://single-1.default.{$your-domain}/switch
        condition: "[@this].#(source==client)" #object matching
      - serviceUrl: http://single-2.default.{$your-domain}/switch
        condition: "instances.#(intval>10)" #array matching
      - serviceUrl: http://single-3.default.{$your-domain}/switch 
        condition: "instances.#(strval%*red-server*)" #pattern matching
