apiVersion: v1
kind: Service
metadata:
  labels:
    group: sklearn-v2-iris-rest-v2
  name: sklearn-v2-iris-rest-v2
  namespace: kserve-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    disvc.group: sklearn-v2-iris-rest-v2
  sessionAffinity: ClientIP
  type: ClusterIP
