apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: minimal
  namespace: istio-system
spec:
  addons:
    grafana:
      enabled: false
    kiali:
      name: kiali
      enabled: true
    prometheus:
      enabled: false
    jaeger: 
      name: jaeger
  security:
    dataPlane:
      mtls: true
    identity:
      type: ThirdParty        
  techPreview:
    meshConfig:
      defaultConfig:
        terminationDrainDuration: 35s
  gateways:
    ingress:
      service:
        metadata:
          labels:
            knative: ingressgateway
  proxy:
    networking:
      trafficControl:
        inbound:
          excludedPorts:
            - 8444 # metrics
            - 8022 # serving: wait-for-drain k8s pre-stop hook        
  profiles:
    - default
