// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: api/proto/v1/modelserving/modelserving.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Application struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Opensource       bool            `protobuf:"varint,2,opt,name=opensource,proto3" json:"opensource,omitempty"`
	CsvName          string          `protobuf:"bytes,3,opt,name=csvName,proto3" json:"csvName,omitempty"`
	Version          string          `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Installed        bool            `protobuf:"varint,5,opt,name=installed,proto3" json:"installed,omitempty"`
	MarketplaceImage bool            `protobuf:"varint,6,opt,name=marketplaceImage,proto3" json:"marketplaceImage,omitempty"`
	Support          *Support        `protobuf:"bytes,7,opt,name=support,proto3" json:"support,omitempty"`
	Integration      *ODHIntegration `protobuf:"bytes,8,opt,name=integration,proto3" json:"integration,omitempty"`
	Example          string          `protobuf:"bytes,9,opt,name=example,proto3" json:"example,omitempty"`
}

func (x *Application) Reset() {
	*x = Application{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP(), []int{1}
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetOpensource() bool {
	if x != nil {
		return x.Opensource
	}
	return false
}

func (x *Application) GetCsvName() string {
	if x != nil {
		return x.CsvName
	}
	return ""
}

func (x *Application) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Application) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *Application) GetMarketplaceImage() bool {
	if x != nil {
		return x.MarketplaceImage
	}
	return false
}

func (x *Application) GetSupport() *Support {
	if x != nil {
		return x.Support
	}
	return nil
}

func (x *Application) GetIntegration() *ODHIntegration {
	if x != nil {
		return x.Integration
	}
	return nil
}

func (x *Application) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type Support struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isv    bool `protobuf:"varint,1,opt,name=isv,proto3" json:"isv,omitempty"`
	Redhat bool `protobuf:"varint,2,opt,name=redhat,proto3" json:"redhat,omitempty"`
}

func (x *Support) Reset() {
	*x = Support{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Support) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Support) ProtoMessage() {}

func (x *Support) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Support.ProtoReflect.Descriptor instead.
func (*Support) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP(), []int{2}
}

func (x *Support) GetIsv() bool {
	if x != nil {
		return x.Isv
	}
	return false
}

func (x *Support) GetRedhat() bool {
	if x != nil {
		return x.Redhat
	}
	return false
}

type ODHIntegration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstallDocUrl string `protobuf:"bytes,1,opt,name=install_doc_url,json=installDocUrl,proto3" json:"install_doc_url,omitempty"`
	Level         string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *ODHIntegration) Reset() {
	*x = ODHIntegration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ODHIntegration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ODHIntegration) ProtoMessage() {}

func (x *ODHIntegration) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ODHIntegration.ProtoReflect.Descriptor instead.
func (*ODHIntegration) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP(), []int{3}
}

func (x *ODHIntegration) GetInstallDocUrl() string {
	if x != nil {
		return x.InstallDocUrl
	}
	return ""
}

func (x *ODHIntegration) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type GetSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *GetSubscribeRequest) Reset() {
	*x = GetSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeRequest) ProtoMessage() {}

func (x *GetSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscribeRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetSubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
}

func (x *GetSubscribeResponse) Reset() {
	*x = GetSubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribeResponse) ProtoMessage() {}

func (x *GetSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_modelserving_modelserving_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribeResponse.ProtoReflect.Descriptor instead.
func (*GetSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscribeResponse) GetSubscribe() *Subscribe {
	if x != nil {
		return x.Subscribe
	}
	return nil
}

var File_api_proto_v1_modelserving_modelserving_proto protoreflect.FileDescriptor

var file_api_proto_v1_modelserving_modelserving_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x76, 0x31, 0x22, 0x27, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xb6, 0x02, 0x0a, 0x0b,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x73, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x73, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65,
	0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a,
	0x07, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x07, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x44, 0x48, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x73, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x69, 0x73,
	0x76, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x64, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x64, 0x68, 0x61, 0x74, 0x22, 0x4e, 0x0a, 0x0e, 0x4f, 0x44, 0x48,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x64, 0x6f, 0x63, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x44, 0x6f, 0x63,
	0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x43, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x32, 0x51, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e,
	0x67, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4a, 0x6f, 0x6f, 0x68, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_modelserving_modelserving_proto_rawDescOnce sync.Once
	file_api_proto_v1_modelserving_modelserving_proto_rawDescData = file_api_proto_v1_modelserving_modelserving_proto_rawDesc
)

func file_api_proto_v1_modelserving_modelserving_proto_rawDescGZIP() []byte {
	file_api_proto_v1_modelserving_modelserving_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_modelserving_modelserving_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_modelserving_modelserving_proto_rawDescData)
	})
	return file_api_proto_v1_modelserving_modelserving_proto_rawDescData
}

var file_api_proto_v1_modelserving_modelserving_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_modelserving_modelserving_proto_goTypes = []interface{}{
	(*Subscribe)(nil),            // 0: v1.Subscribe
	(*Application)(nil),          // 1: v1.Application
	(*Support)(nil),              // 2: v1.Support
	(*ODHIntegration)(nil),       // 3: v1.ODHIntegration
	(*GetSubscribeRequest)(nil),  // 4: v1.GetSubscribeRequest
	(*GetSubscribeResponse)(nil), // 5: v1.GetSubscribeResponse
}
var file_api_proto_v1_modelserving_modelserving_proto_depIdxs = []int32{
	2, // 0: v1.Application.support:type_name -> v1.Support
	3, // 1: v1.Application.integration:type_name -> v1.ODHIntegration
	0, // 2: v1.GetSubscribeResponse.subscribe:type_name -> v1.Subscribe
	4, // 3: v1.ModelServing.GetSubscribe:input_type -> v1.GetSubscribeRequest
	5, // 4: v1.ModelServing.GetSubscribe:output_type -> v1.GetSubscribeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_modelserving_modelserving_proto_init() }
func file_api_proto_v1_modelserving_modelserving_proto_init() {
	if File_api_proto_v1_modelserving_modelserving_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_modelserving_modelserving_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_modelserving_modelserving_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Application); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_modelserving_modelserving_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Support); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_modelserving_modelserving_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ODHIntegration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_modelserving_modelserving_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_modelserving_modelserving_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_modelserving_modelserving_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_modelserving_modelserving_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_modelserving_modelserving_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_modelserving_modelserving_proto_msgTypes,
	}.Build()
	File_api_proto_v1_modelserving_modelserving_proto = out.File
	file_api_proto_v1_modelserving_modelserving_proto_rawDesc = nil
	file_api_proto_v1_modelserving_modelserving_proto_goTypes = nil
	file_api_proto_v1_modelserving_modelserving_proto_depIdxs = nil
}
