apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
  name: showcase 
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"    
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - image: quay.io/openshift-knative/showcase 
          env:
            - name: GREET 
              value: Ciao
