apiVersion: v1
kind: Pod
metadata:
  name: egress-1
  labels:
    name: egress-1
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  containers:
  - name: egress-router
    image: openshift/origin-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 192.168.200.123
    - name: EGRESS_GATEWAY 
      value: 192.168.200.1
    - name: EGRESS_DESTINATION 
      value: 192.168.200.203
  nodeSelector:
    egress-router: "true"
